# Generated by Django 6.1 on 2026-08-31 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_customer_store_custo_last_na_2e448d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel an order')]},
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_user_id_5b583a_idx',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='store_custo_phone_eb16a7_idx'),
        ),
    ]
